## **Introduction: Analyzing User Behavior and Conversion Metrics by Gender, Age, and time**

## Demographics

In this analysis, I explored the relationship between user demographics (gender and age) and key performance indicators (KPIs) such as impressions, clicks, and conversions. The goal was to understand if there were statistically significant differences between men and women in terms of these metrics and if age had any impact on conversion and click-through rates (CTR).

To achieve this, I applied a series of hypothesis tests and analysis of variance (ANOVA) techniques, including:

1. **Hypothesis Test for Gender Differences**: I performed a hypothesis test to determine whether women had more impressions, clicks, and conversions than men. Using the resultant p-value and an alpha of 0.05, women have a statisitically different amount of impressions and clicks. However, there is no difference in conversions between men and women.
  
2. **2-Way Z-Test for Conversion (CVR) and Click Rates (CTR)**: A two-way z-test was used to investigate conversion and click rates by gender. Using an alpha of 0.05 again, it was found that there is no significant difference between CVR or CTR for men and women. Even though women were the majority of impressions and clicks, they both had the same overall CVR and CTR.
  
3. **One-Way ANOVA for Age Effect**: I conducted a one-way ANOVA to assess whether age influenced conversion rates, as it was revealed gender does not. The test revealed that age had no significant effect on CVR.

4. **One-Way ANOVA for Gender and KPIs**: A one-way ANOVA was also performed to see if gender had an effect on conversion rates. The test revealed that gender had no significant effect on CVR, which can be seen in the z-test as well.

5. **Two-Way ANOVA with Post-Hoc Tukey Test**: To refine the analysis, a two-way ANOVA with a post-hoc Tukey test was applied to assess the effect of both age and gender on conversion rates. Using a 0.05 value for alpha, there was no significant difference between any of the categories. However, upon further analysis in the post-hoc tukey test, it was found that the following pairs had a p value of less than 0.1, which is also a valid alpha choice.
  - Age groups 18-25 and 55+
  - Women in the age group 18-25 and men in the age group 55+

 This suggests that older age groups, and older men specifically, are more likely to convert than the younger age groups, young women specifically. This makes sense, as older age groups are more likely to have money to spend on entertainment than the younger age groups.

This series of analyses provides valuable insights into how user demographics may affect conversion behaviors and helps identify actionable trends for improving performance across different user groups.

## Time Analysis

 For this analysis, I examined data from an advertising campaign that was run over the course of two different weeks.

 **Week 1**, I performed a one-way ANOVA test to determine if there were significant differences in impressions, clicks, and conversions across different days of the week. The results revealed a significant difference, with Sunday leading in all three metrics, followed by Saturday. To further explore the differences between the days, I used a post-hoc Tukey test, which compared all the days in pairs.

**Week 2**, I found that the data was insufficient to run an ANOVA test, so I evaluated the trends manually. I observed that Wednesday and Tuesday outperformed the other days in impressions, clicks, and conversions. Monday lagged behind in impressions and clicks but was relatively consistent with other days in terms of conversions. Thursday and Friday consistently had low performance across all metrics.

Lastly, I conducted an ANOVA test for impressions by hour of the day for week 1. The results showed no significant variance between hours, even with a p-value < 0.1. However, I did identify that the top 5 times for impressions were consistently around 300 impressions, with the peak time being over 500 impressions. The top 5 times, in order, were: 8 PM, 10 PM, 9 PM, 7 PM, and 6 PM—all occurring during the evening when people are generally more available after work and school.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Importing Data

In [ ]:
camp_data = pd.read_csv('tiktok ads campaign data.csv')

In [ ]:
dem_data = pd.read_csv('tiktok_ads_demographics.csv')

In [ ]:
time_week1 = pd.read_csv('tiktok_time_week1.csv')

In [ ]:
time_week2 = pd.read_csv('tiktok_time_week2.csv')

In [ ]:
dem_data.head()

,Age,Gender,Cost,Impressions,Clicks (destination),Conversions,CTR (destination),Conversion rate (CVR),CPC (destination),CPM,Cost per conversion
0,35-44,Female,26.80,3326,126,45,3.79%,1.35%,0.21,8.06,0.60
1,25-34,Female,24.89,4026,128,40,3.18%,0.99%,0.19,6.18,0.62
2,45-54,Female,20.10,1899,69,26,3.63%,1.37%,0.29,10.58,0.77
3,≥55,Female,10.34,814,32,9,3.93%,1.11%,0.32,12.70,1.15
4,45-54,Male,8.32,811,26,10,3.21%,1.23%,0.32,10.26,0.83

In [ ]:
dem_data.groupby('Gender')['Impressions'].sum()

Gender
Female     11367
Male        4020
Unknown      122
Name: Impressions, dtype: int64

## Begin statistical analysis

In [ ]:
from scipy import stats
from statsmodels.stats.proportion import proportions_ztest

In [ ]:
#Use a 2-sample z proportion test to see if the amount of impressions is significantly different for women and men.

male_impressions = 4020  # Total number of male impressions
female_impressions = 11367  # Total number of female impressions
total_impressions = male_impressions + female_impressions  # Combined total impressions

# Count of male and female viewers
imp_counts = np.array([male_impressions, female_impressions])

# Number of groups (two groups: male and female)
impressions_n = np.array([total_impressions, total_impressions])  # Number of total impressions in each group

# Perform a z-test for proportions
stat_impressions, p_value_impressions = proportions_ztest(imp_counts, impressions_n)

# Print results

print(f"Z-statistic: {stat_impressions}")
print(f"P-value: {p_value_impressions}")

# Interpret the result
alpha = 0.05  # Significance level of 5%

if p_value_impressions < alpha:
    print("Reject the null hypothesis: There is a significant difference between male and female impressions.")
else:
    print("Fail to reject the null hypothesis: No significant difference between male and female impressions.")

Z-statistic: -83.76219716328238
P-value: 0.0
Reject the null hypothesis: There is a significant difference between male and female impressions.

In [ ]:
dem_data.rename(columns={'Clicks (destination)': 'Clicks'}, inplace=True)

In [ ]:
dem_data.groupby('Gender')['Clicks'].sum()

Gender
Female     386
Male       143
Unknown      6
Name: Clicks, dtype: int64

In [ ]:
#Use a 2-sample z proportion test to see if the amount of clicks is significantly different for women and men.
male = 143  # Total number of male clicks
female = 386  # Total number of female clicks
total = male + female  # Combined total clicks

# Count of male and female clicks
counts = np.array([male, female])

# Number of groups (two groups: male and female)
n = np.array([total, total])  # Number of total clicks in each group

# Perform a z-test for proportions
stat, p_value = proportions_ztest(counts, n)

# Print results

print(f"Z-statistic: {stat}")
print(f"P-value: {p_value}")

# Interpret the result
alpha = 0.05  # Significance level of 5%

if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between male and female clicks.")
else:
    print("Fail to reject the null hypothesis: No significant difference between male and female clicks.")

Z-statistic: -14.941473724202698
P-value: 1.770166676730958e-50
Reject the null hypothesis: There is a significant difference between male and female clicks.

In [ ]:
dem_data.groupby('Gender')['Conversions'].sum()

Gender
Female     128
Male        47
Unknown      1
Name: Conversions, dtype: int64

In [ ]:
#Use a 2-sample z proportion test to see if the amount of conversions is significantly different for women and men.
male = 128  # Total number of male conversions
female = 47  # Total number of female conversions
total = male + female  # Combined total conversions

# Count of male and female viewers
counts = np.array([male, female])

# Number of groups (two groups: male and female)
n = np.array([total, total])  # Number of total conversions in each group

# Perform a z-test for proportions
stat, p_value = proportions_ztest(counts, n)

# Print results

print(f"Z-statistic: {stat}")
print(f"P-value: {p_value}")

# Interpret the result
alpha = 0.05  # Significance level of 5%

if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between male and female conversions.")
else:
    print("Fail to reject the null hypothesis: No significant difference between male and female conversions.")

Z-statistic: 8.65926423796255
P-value: 4.748190009149622e-18
Reject the null hypothesis: There is a significant difference between male and female conversions.

In [ ]:
dem_data['CVR'] = dem_data['Conversions'] / dem_data['Impressions']

In [ ]:
dem_data['CTR'] = dem_data['Clicks'] / dem_data['Impressions']

In [ ]:
dem_data.groupby('Gender')[['Clicks','Conversions','Impressions']].sum()

         Clicks  Conversions  Impressions
Gender
Female      386          128        11367
Male        143           47         4020
Unknown       6            1          122

In [ ]:
# Use a z test to compare click through rates between male and females
# success counts and total viewers for CTR
male_successes = 143  # Number of clicks for males
female_successes = 386  # Number of clicks for females
male_total = 4020  # Total number of male views
female_total = 11367  # Total number of female views

# Counts of successes for male and female
successes = np.array([female_successes, male_successes])

# Total number of trials for male and female
n = np.array([female_total, male_total])

# Perform the z-test for proportions
z_stat, p_value = proportions_ztest(successes, n)

# Print results
print(f"Z-statistic: {z_stat}")
print(f"P-value: {p_value}")

# Interpretation of results
alpha = 0.05  # Industry standard significance level of 5%

if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between male and female click through rate.")
elif p_value < 0.1:
    print("Moderate evidence against the null hypothesis: There is a moderate difference between male and female click through rate.")
else:
    print("Fail to reject the null hypothesis: No significant difference between male and female click through rate.")

Z-statistic: -0.4827917089346444
P-value: 0.6292436383699052
Fail to reject the null hypothesis: No significant difference between male and female click through rate.

In [ ]:
# Use a z test to compare conversion rates between male and females
# success counts and total viewers for CVR
male_successes = 47  # Number of successful male viewers
female_successes = 128  # Number of successful female viewers
male_total = 4020  # Total number of male viewers
female_total = 11367  # Total number of female viewers

# Counts of successes for male and female
successes = np.array([female_successes, male_successes])

# Total number of trials for male and female
n = np.array([female_total, male_total])

# Perform the z-test for proportions
z_stat, p_value = proportions_ztest(successes, n)

# Print results
print(f"Z-statistic: {z_stat}")
print(f"P-value: {p_value}")

# Interpretation of results
alpha = 0.05  # Industry standard significance level of 5%

if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between male and female conversion rates.")
elif p_value < 0.1:
    print("Moderate evidence against the null hypothesis: There is a moderate difference between male and female conversion rates.")
else:
    print("Fail to reject the null hypothesis: No significant difference between male and female conversion rates.")

Z-statistic: -0.2214381765792326
P-value: 0.8247512695325454
Fail to reject the null hypothesis: No significant difference between male and female conversion rates.

In [ ]:
dem_data_CVR = (dem_data.groupby('Age')['Conversions'].sum() / dem_data.groupby('Age')['Impressions'].sum())

In [ ]:
dem_data_CVR

Age
18-24      0.006645
25-34      0.010290
35-44      0.012475
45-54      0.013573
Unknown    0.000000
≥55        0.013889
dtype: float64

use table to compare top to bottom CVRs

In [ ]:
dem_data_CTR = (dem_data.groupby('Age')['Clicks'].sum() / dem_data.groupby('Age')['Impressions'].sum())

In [ ]:
dem_data_CTR

Age
18-24      0.023810
25-34      0.033727
35-44      0.036534
45-54      0.036317
Unknown    0.000000
≥55        0.042484
dtype: float64

In [ ]:
dem_data.groupby('Age')[['Clicks','Conversions','Impressions']].sum()

         Clicks  Conversions  Impressions
Age
18-24        43           12         1806
25-34       177           54         5248
35-44       164           56         4489
45-54        99           37         2726
Unknown       0            0           16
≥55          52           17         1224

In [ ]:
import scipy.stats as stats

# One-way ANOVA: Testing conversion rates across different Age Groups
age_groups = dem_data['Age']
conversion_rates = dem_data['CVR']

# Perform the one-way ANOVA
f_stat, p_value = stats.f_oneway(
    *[conversion_rates[age_groups == group] for group in dem_data['Age'].unique()]
)

# Output the results
print(f"F-statistic: {f_stat}")
print(f"P-value: {p_value}")

# Decision based on p-value
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between age groups.")
elif p_value < 0.1:
    print("Moderate evidence against the null hypothesis: There is a moderate difference between age groups.")
else:
    print("Fail to reject the null hypothesis: No significant difference between age groups.")

F-statistic: 1.3055326293859983
P-value: 0.3356341254848338
Fail to reject the null hypothesis: No significant difference between age groups.

I have some concerns about the ANOVA test, as I feel there may be insufficient data. I believe there should be variability in conversion rate (CVR) across different age groups. I will perform a post-hoc test to analyze the pair-wise data.

In [ ]:
# Perform post-hoc test using tukey HSD to see if any pairs have a p value of under 0.1 or close
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Perform Tukey's HSD test
tukey_results = pairwise_tukeyhsd(dem_data['CVR'], dem_data['Age'], alpha=0.05)

# Display Tukey's test results
print(tukey_results)

 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
 group1  group2 meandiff p-adj   lower  upper  reject
-----------------------------------------------------
  18-24   25-34   0.0025 0.9999 -0.0382 0.0431  False
  18-24   35-44    0.003 0.9998 -0.0377 0.0436  False
  18-24   45-54   0.0247 0.3517 -0.0159 0.0654  False
  18-24 Unknown  -0.0048 0.9996 -0.0622 0.0527  False
  18-24     ≥55   0.0056 0.9958  -0.035 0.0463  False
  25-34   35-44   0.0005    1.0 -0.0401 0.0411  False
  25-34   45-54   0.0223 0.4516 -0.0184 0.0629  False
  25-34 Unknown  -0.0072 0.9973 -0.0647 0.0502  False
  25-34     ≥55   0.0032 0.9997 -0.0374 0.0438  False
  35-44   45-54   0.0218 0.4735 -0.0189 0.0624  False
  35-44 Unknown  -0.0077 0.9963 -0.0652 0.0497  False
  35-44     ≥55   0.0027 0.9999 -0.0379 0.0433  False
  45-54 Unknown  -0.0295 0.5145  -0.087 0.0279  False
  45-54     ≥55  -0.0191 0.5982 -0.0597 0.0215  False
Unknown     ≥55   0.0104 0.9859  -0.047 0.0679  False
-----------------------------------------------------

In [ ]:
import scipy.stats as stats

# One-way ANOVA: Testing conversion rates across different genders
gender_groups = dem_data['Gender']
conversion_rates = dem_data['CVR']

# Perform the one-way ANOVA
f_stat, p_value = stats.f_oneway(
    *[conversion_rates[gender_groups == group] for group in dem_data['Gender'].unique()]
)

# Output the results
print(f"F-statistic: {f_stat}")
print(f"P-value: {p_value}")

# Decision based on p-value
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between genders.")
elif p_value < 0.1:
    print("Moderate evidence against the null hypothesis: There is a moderate difference between genders.")
else:
    print("Fail to reject the null hypothesis: No significant difference between genders.")

F-statistic: 0.0228046979830761
P-value: 0.9774923755205904
Fail to reject the null hypothesis: No significant difference between genders.

This was expected, as in earlier calculations I found there is no significant difference in CVR by gender using a 2 sample z-test. However, I will still perform the same post-hoc test for completion.

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
# Perform post-hoc test using tukey HSD to see if any pairs have a p value of under 0.1 or close

tukey_results = pairwise_tukeyhsd(dem_data['CVR'], dem_data['Gender'], alpha=0.05)

# Display Tukey's test results
print(tukey_results)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
group1  group2 meandiff p-adj   lower  upper  reject
----------------------------------------------------
Female    Male   0.0016 0.9871 -0.0254 0.0285  False
Female Unknown  -0.0005 0.9988 -0.0262 0.0253  False
  Male Unknown   -0.002 0.9767 -0.0278 0.0238  False
----------------------------------------------------

While I expected the outcome of the gender ANOVA test, I am still not confident in the age test. I am going to run a 2 way anova test for gender and age to see if that effects the outcome, and then a perform the post-hoc test using tukey's HSD to see what groups are different. If there are none, it may be due to having too litte data.

In [ ]:
dem_data['Age'] = pd.Categorical(dem_data['Age'])
dem_data['Gender'] = pd.Categorical(dem_data['Gender'])

In [ ]:
dem_data.groupby(['Age', 'Gender'])[['Clicks','Conversions','Impressions', 'CVR']].mean()

<ipython-input-50-1b199dd98034>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dem_data.groupby(['Age', 'Gender'])[['Clicks','Conversions','Impressions', 'CVR']].mean()

                 Clicks  Conversions  Impressions       CVR
Age     Gender
18-24   Female     31.0          8.0       1302.0  0.006144
        Male       12.0          4.0        489.0  0.008180
        Unknown     0.0          0.0         15.0  0.000000
25-34   Female    128.0         40.0       4026.0  0.009935
        Male       48.0         14.0       1188.0  0.011785
        Unknown     1.0          0.0         34.0  0.000000
35-44   Female    126.0         45.0       3326.0  0.013530
        Male       37.0         11.0       1136.0  0.009683
        Unknown     1.0          0.0         27.0  0.000000
45-54   Female     69.0         26.0       1899.0  0.013691
        Male       26.0         10.0        811.0  0.012330
        Unknown     4.0          1.0         16.0  0.062500
Unknown Female      NaN          NaN          NaN       NaN
        Male        NaN          NaN          NaN       NaN
        Unknown     0.0          0.0         16.0  0.000000
≥55     Female     32.0          9.0        814.0  0.011057
        Male       20.0          8.0        396.0  0.020202
        Unknown     0.0          0.0         14.0  0.000000

In [157]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

# attempting a 2 way anova test
data = {
    'Age Group': ['18-24', '18-24', '25-34', '25-34', '35-44', '35-44', '45-54', '45-54', '55+', '55+'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Conversion Rate': [0.8180, 0.6144, 0.11785, 0.9935, 0.9683, 1.353, 1.233, 1.3691, 2.0202, 1.1057]
}

df = pd.DataFrame(data)

# Convert to categorical variables
df['Age Group'] = pd.Categorical(df['Age Group'])
df['Gender'] = pd.Categorical(df['Gender'])

# Perform Two-Way ANOVA
model = ols('Q("Conversion Rate") ~ C(Q("Age Group")) + C(Gender) + C(Q("Age Group")):C(Gender)', data=df).fit()

# Get the ANOVA table
anova_table = anova_lm(model)

# Output the results
print(anova_table)

                              df        sum_sq   mean_sq    F  PR(>F)
C(Q("Age Group"))            4.0  1.387468e+00  0.346867  0.0     NaN
C(Gender)                    1.0  7.747872e-03  0.007748  0.0     NaN
C(Q("Age Group")):C(Gender)  4.0  8.977738e-01  0.224443  0.0     NaN
Residual                     0.0  5.423611e-30       inf  NaN     NaN

/usr/local/lib/python3.11/dist-packages/statsmodels/stats/anova.py:142: RuntimeWarning: divide by zero encountered in scalar divide
  (model.ssr / model.df_resid))

Since the ANOVA test returned a NAN for the p-value, the dataset is likely too small. To demonstrate for educational purposes, I will generate additional data and use the average conversion rates for each age group.

In [ ]:
dem_data.groupby(['Age','Gender'])[['Clicks','Conversions','Impressions', 'CVR']].mean()

<ipython-input-52-0b33777a64b5>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dem_data.groupby(['Age','Gender'])[['Clicks','Conversions','Impressions', 'CVR']].mean()

                 Clicks  Conversions  Impressions       CVR
Age     Gender
18-24   Female     31.0          8.0       1302.0  0.006144
        Male       12.0          4.0        489.0  0.008180
        Unknown     0.0          0.0         15.0  0.000000
25-34   Female    128.0         40.0       4026.0  0.009935
        Male       48.0         14.0       1188.0  0.011785
        Unknown     1.0          0.0         34.0  0.000000
35-44   Female    126.0         45.0       3326.0  0.013530
        Male       37.0         11.0       1136.0  0.009683
        Unknown     1.0          0.0         27.0  0.000000
45-54   Female     69.0         26.0       1899.0  0.013691
        Male       26.0         10.0        811.0  0.012330
        Unknown     4.0          1.0         16.0  0.062500
Unknown Female      NaN          NaN          NaN       NaN
        Male        NaN          NaN          NaN       NaN
        Unknown     0.0          0.0         16.0  0.000000
≥55     Female     32.0          9.0        814.0  0.011057
        Male       20.0          8.0        396.0  0.020202
        Unknown     0.0          0.0         14.0  0.000000

In [ ]:
import pandas as pd
import numpy as np

# Set a seed for reproducibility
np.random.seed(42)

# Define the parameters for the simulation
n = 1000  # number of observations per group
age_groups = ['18-24', '25-34', '35-44', '45-54', '55+']
genders = ['Male', 'Female']

# Simulate the Age Group column (randomly assign age groups)
# Changed size to n to match the intended number of observations
age_group = np.random.choice(age_groups, size=n, replace=True)

# Simulate the Gender column (randomly assign gender)
# Changed size to n to match the intended number of observations
gender = np.random.choice(genders, size=n, replace=True)

# Simulate Conversion Rates
# Assuming conversion rates are between 0 and 1, we can simulate using a normal distribution
# For simplicity and to keep the results consistent with the data, I set the mean conversion rates for each gender and age group from the table
mean_conversion_rate = {
    'Male': [0.008180, .011785 , .009683, .012330, .020202],
    'Female': [.006144, 0.009935, .01353, .013691, .011057]
}

# Generate conversion rates based on gender and age group
conversion_rates = []
for a, g in zip(age_group, gender):
    # Get the mean for the corresponding age group and gender
    age_index = age_groups.index(a)
    conversion_rates.append(np.random.normal(loc=mean_conversion_rate[g][age_index], scale=0.05))  # small variation (std=0.05)

# Create the DataFrame
df = pd.DataFrame({
    'Age Group': age_group,
    'Gender': gender,
    'Conversion Rate': conversion_rates
})

print(df.head())

  Age Group  Gender  Conversion Rate
0     45-54  Female         0.083659
1       55+  Female         0.057289
2     35-44  Female         0.016512
3       55+  Female        -0.021290
4       55+  Female         0.045968

Now, I am going to compare the original data set with the new data set to make sure it seems close enough to the original rates.

In [ ]:
df.groupby(['Gender', 'Age Group'])[['Conversion Rate']].mean()

                  Conversion Rate
Gender Age Group
Female 18-24             0.005111
       25-34             0.010563
       35-44             0.012082
       45-54             0.020928
       55+               0.019357
Male   18-24             0.014963
       25-34             0.016160
       35-44             0.013566
       45-54             0.012667
       55+               0.025944

In [ ]:
dem_data.groupby(['Gender','Age'])['CVR'].mean()

<ipython-input-75-3b9722e12ea6>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dem_data.groupby(['Gender','Age'])['CVR'].mean()

Gender   Age
Female   18-24      0.006144
         25-34      0.009935
         35-44      0.013530
         45-54      0.013691
         Unknown         NaN
         ≥55        0.011057
Male     18-24      0.008180
         25-34      0.011785
         35-44      0.009683
         45-54      0.012330
         Unknown         NaN
         ≥55        0.020202
Unknown  18-24      0.000000
         25-34      0.000000
         35-44      0.000000
         45-54      0.062500
         Unknown    0.000000
         ≥55        0.000000
Name: CVR, dtype: float64

While different, it is still close enough for this purpose for me to use.

In [156]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

# Perform Two-Way ANOVA
model = ols('Q("Conversion Rate") ~ C(Q("Age Group")) + C(Gender) + C(Q("Age Group")):C(Gender)', data=df).fit()

# Get the ANOVA table
anova_table = anova_lm(model)

# Output the results
print(anova_table)

                                df    sum_sq   mean_sq         F    PR(>F)
C(Q("Age Group"))              4.0  0.018129  0.004532  1.814359  0.123820
C(Gender)                      1.0  0.002320  0.002320  0.928824  0.335404
C(Q("Age Group")):C(Gender)    4.0  0.010051  0.002513  1.005966  0.403338
Residual                     990.0  2.472953  0.002498       NaN       NaN

Now that there is enough data the p valuen is no longer NAN and can be used for evaluation.
- Age Group: The p-value is bigger than both 0.05 and 0.1, therefore I fail to reject the null hypothesis and cannot claim that any age group is different.

- Gender: The p value is bigger than both 0.05 and 0.1, so I fail to reject the null hypothesis and conclude that Gender does not significantly affect the conversion rate.

- Interaction (Age Group x Gender): The p-value for the interaction term is greater than 0.05 and 0.1, so I fail to reject the null hypothesis and conclude that there is no significant interaction between Age Group and Gender in affecting conversion rates.

Since this is not the real data, it is not a perfect representation of the data, but it can be considered for the case of this project.

Now I will conduct the post-hoc tukey test to see if any individual groups are close enough (around 0.1) to be considered statistically different.

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [ ]:
tukey_age = pairwise_tukeyhsd(df['Conversion Rate'], df['Age Group'])
print(tukey_age)

# Tukey's HSD test for 'Gender' main effect
tukey_gender = pairwise_tukeyhsd(df['Conversion Rate'], df['Gender'])
print(tukey_gender)

# Tukey's HSD test for 'Age Group' and 'Gender' interaction
# First, you need to create a new factor that combines both 'Age Group' and 'Gender'
df['Age_Gender'] = df['Age Group'] + ' - ' + df['Gender']
tukey_interaction = pairwise_tukeyhsd(df['Conversion Rate'], df['Age_Gender'])
print(tukey_interaction)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
 18-24  25-34   0.0033 0.9663 -0.0104 0.0169  False
 18-24  35-44   0.0024 0.9891 -0.0113 0.0161  False
 18-24  45-54   0.0062 0.7088 -0.0072 0.0196  False
 18-24    55+   0.0123 0.0928 -0.0012 0.0257  False
 25-34  35-44  -0.0009 0.9998 -0.0149 0.0132  False
 25-34  45-54    0.003 0.9765 -0.0108 0.0167  False
 25-34    55+    0.009 0.3832 -0.0048 0.0228  False
 35-44  45-54   0.0038 0.9415 -0.0099 0.0176  False
 35-44    55+   0.0098 0.2893 -0.0039 0.0236  False
 45-54    55+    0.006 0.7399 -0.0075 0.0195  False
---------------------------------------------------
Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================
group1 group2 meandiff p-adj   lower  upper  reject
---------------------------------------------------
Female   Male   0.0029 0.3576 -0.0033 0.0091  False
---------------------------------------------------
        Multiple Comparison of Means - Tukey HSD, FWER=0.05
===================================================================
    group1         group2     meandiff p-adj   lower  upper  reject
-------------------------------------------------------------------
18-24 - Female   18-24 - Male   0.0099 0.9194 -0.0121 0.0318  False
18-24 - Female 25-34 - Female   0.0055 0.9993  -0.018 0.0289  False
18-24 - Female   25-34 - Male    0.011 0.8622 -0.0113 0.0334  False
18-24 - Female 35-44 - Female    0.007  0.993 -0.0154 0.0294  False
18-24 - Female   35-44 - Male   0.0085  0.979 -0.0148 0.0317  False
18-24 - Female 45-54 - Female   0.0158 0.4468 -0.0068 0.0385  False
18-24 - Female   45-54 - Male   0.0076 0.9862 -0.0146 0.0297  False
18-24 - Female   55+ - Female   0.0142 0.5851 -0.0081 0.0366  False
18-24 - Female     55+ - Male   0.0208 0.0962 -0.0016 0.0433  False
  18-24 - Male 25-34 - Female  -0.0044 0.9998 -0.0271 0.0183  False
  18-24 - Male   25-34 - Male   0.0012    1.0 -0.0204 0.0228  False
  18-24 - Male 35-44 - Female  -0.0029    1.0 -0.0246 0.0188  False
  18-24 - Male   35-44 - Male  -0.0014    1.0  -0.024 0.0212  False
  18-24 - Male 45-54 - Female    0.006 0.9974  -0.016 0.0279  False
  18-24 - Male   45-54 - Male  -0.0023    1.0 -0.0237 0.0191  False
  18-24 - Male   55+ - Female   0.0044 0.9998 -0.0172  0.026  False
  18-24 - Male     55+ - Male    0.011 0.8477 -0.0108 0.0327  False
25-34 - Female   25-34 - Male   0.0056  0.999 -0.0175 0.0287  False
25-34 - Female 35-44 - Female   0.0015    1.0 -0.0217 0.0247  False
25-34 - Female   35-44 - Male    0.003    1.0  -0.021  0.027  False
25-34 - Female 45-54 - Female   0.0104 0.9262 -0.0131 0.0338  False
25-34 - Female   45-54 - Male   0.0021    1.0 -0.0208  0.025  False
25-34 - Female   55+ - Female   0.0088 0.9717 -0.0144 0.0319  False
25-34 - Female     55+ - Male   0.0154 0.5297 -0.0079 0.0386  False
  25-34 - Male 35-44 - Female  -0.0041 0.9999 -0.0262  0.018  False
  25-34 - Male   35-44 - Male  -0.0026    1.0 -0.0255 0.0204  False
  25-34 - Male 45-54 - Female   0.0048 0.9996 -0.0175 0.0271  False
  25-34 - Male   45-54 - Male  -0.0035    1.0 -0.0253 0.0183  False
  25-34 - Male   55+ - Female   0.0032    1.0 -0.0188 0.0252  False
  25-34 - Male     55+ - Male   0.0098 0.9269 -0.0124 0.0319  False
35-44 - Female   35-44 - Male   0.0015    1.0 -0.0216 0.0245  False
35-44 - Female 45-54 - Female   0.0088 0.9637 -0.0136 0.0313  False
35-44 - Female   45-54 - Male   0.0006    1.0 -0.0213 0.0225  False
35-44 - Female   55+ - Female   0.0073 0.9896 -0.0149 0.0294  False
35-44 - Female     55+ - Male   0.0139 0.6164 -0.0084 0.0361  False
  35-44 - Male 45-54 - Female   0.0074 0.9921 -0.0159 0.0306  False
  35-44 - Male   45-54 - Male  -0.0009    1.0 -0.0237 0.0219  False
  35-44 - Male   55+ - Female   0.0058 0.9986 -0.0172 0.0288  False
  35-44 - Male     55+ - Male   0.0124 0.7965 -0.0107 0.0355  False
45-54 - Female   45-54 - Male  -0.0083 0.9746 -0.0304 0.0138  False
45-54 - Female   55+ - Female  -0.0016    1.0 -0.0239 0.0208  False
45-54 - Female     55+ - Male    0.005 0.9995 -0.0175 0.0275  False
  45-54 - Male   55+ - Female   0.0067 0.9937 -0.0151 0.0285  False
  45-54 - Male     55+ - Male   0.0133  0.656 -0.0087 0.0352  False
  55+ - Female     55+ - Male   0.0066 0.9951 -0.0156 0.0288  False
-------------------------------------------------------------------

In [ ]:
tukey_age.pvalues < 0.1

array([False, False, False,  True, False, False, False, False, False,
       False])

In [ ]:
tukey_age.pvalues[3]

0.09278272471764437

This could be considered as different or to do further investigation into since the p value is smaller than 0.1 which is sometimes accepted. The pair that has this p value is 18-24 and 55+, meaning the lowest and oldest age groups might have some statistical difference. This makes sense, as older age groups are more likely to have money to spend on entertainment that younger viewers.

In [ ]:
tukey_interaction.pvalues < 0.1

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [ ]:
tukey_interaction.pvalues[8]

0.09619245830318379

When examining the combined evaluation for gender and age, the smallest p-value— and the only one under 0.1— is found between the 18-24 female group and the 55+ male group. This result mirrors the pattern seen in the age-only evaluation, but with the added insight that the largest gap occurs specifically between 18-24-year-old females and 55+ males. This suggests that male viewers over 55+ are more likely to convert than women age 18-24, and possibly the other groups.

## Time Analysis

In [ ]:
time_week1.head()

,Time,Cost,Cost per result,CPC (destination),Impressions,CTR (destination),Clicks (destination),Result rate,Results,Cost per conversion,Conversion rate (CVR),Conversions,Reach,"Cost per 1,000 people reached",Frequency,Currency
0,2024-05-21 16:00 - 16:59,0.0,-,0.0,0,0.00%,0,-,-,0.0,0.00%,0,0,0.0,0.0,USD
1,2024-05-21 10:00 - 10:59,0.0,-,0.0,1,0.00%,0,-,-,0.0,0.00%,0,1,0.0,1.0,USD
2,2024-05-21 06:00 - 06:59,0.0,-,0.0,1,0.00%,0,-,-,0.0,0.00%,0,1,0.0,1.0,USD
3,2024-05-20 19:00 - 19:59,0.0,-,0.0,0,0.00%,0,-,-,0.0,0.00%,0,0,0.0,0.0,USD
4,2024-05-20 18:00 - 18:59,0.0,-,0.0,1,100.00%,1,-,-,0.0,0.00%,0,1,0.0,1.0,USD

In [102]:
time_week1 = pd.read_csv('tiktok_time_week1_ff.csv')

In [103]:
time_week1.head()

,Date,Hour,Impressions,CTR (destination),Clicks (destination),Result rate,Results,Cost per conversion,Conversion rate (CVR),Conversions,Reach,"Cost per 1,000 people reached",Frequency,Currency
0,2024-05-21,16:00,0,0.00%,0,-,-,0.0,0.00%,0,0,0.0,0.0,USD
1,2024-05-21,10:00,1,0.00%,0,-,-,0.0,0.00%,0,1,0.0,1.0,USD
2,2024-05-21,6:00,1,0.00%,0,-,-,0.0,0.00%,0,1,0.0,1.0,USD
3,2024-05-20,19:00,0,0.00%,0,-,-,0.0,0.00%,0,0,0.0,0.0,USD
4,2024-05-20,18:00,1,100.00%,1,-,-,0.0,0.00%,0,1,0.0,1.0,USD

In [106]:
time_week1.rename(columns={'Clicks (destination)': 'Clicks'}, inplace=True)

In [109]:
time_week2.head()

,Date,Cost,Cost per result,CPC (destination),Impressions,CTR (destination),Clicks,Result rate,Results,Cost per conversion,Conversion rate (CVR),Conversions,Reach,"Cost per 1,000 people reached",Frequency,Currency
0,2024-06-28,0.00,-,0.00,1,0.00%,0,-,-,0.00,0.00%,0,1,0.00,1.00,USD
1,2024-06-27,3.30,-,0.25,571,2.28%,13,-,-,1.65,0.35%,2,564,5.85,1.01,USD
2,2024-06-26,21.67,-,0.19,3956,2.93%,116,-,-,0.80,0.68%,27,3692,5.87,1.07,USD
3,2024-06-25,21.14,-,0.22,3383,2.78%,94,-,-,0.62,1.01%,34,3034,6.97,1.12,USD
4,2024-06-24,13.89,-,0.18,1698,4.59%,78,-,-,0.41,2.00%,34,1599,8.69,1.06,USD

In [105]:
time_week2.rename(columns={'By Day': 'Date'}, inplace=True)

In [108]:
time_week2.rename(columns={'Clicks (destination)': 'Clicks'}, inplace=True)

In [120]:
# Convert the 'Date' column to datetime
time_week1['Date'] = pd.to_datetime(time_week1['Date'])

# Extract the weekday name (e.g., Monday, Tuesday, etc.)
time_week1['Weekday'] = time_week1['Date'].dt.strftime('%A')

In [127]:
time_week2['Date'] = pd.to_datetime(time_week2['Date'])

time_week2['Weekday'] = time_week2['Date'].dt.strftime('%A')

In [121]:
time_week1.head()

,Date,Hour,Impressions,CTR (destination),Clicks,Result rate,Results,Cost per conversion,Conversion rate (CVR),Conversions,Reach,"Cost per 1,000 people reached",Frequency,Currency,Weekday
0,2024-05-21,16:00,0,0.00%,0,-,-,0.0,0.00%,0,0,0.0,0.0,USD,Tuesday
1,2024-05-21,10:00,1,0.00%,0,-,-,0.0,0.00%,0,1,0.0,1.0,USD,Tuesday
2,2024-05-21,6:00,1,0.00%,0,-,-,0.0,0.00%,0,1,0.0,1.0,USD,Tuesday
3,2024-05-20,19:00,0,0.00%,0,-,-,0.0,0.00%,0,0,0.0,0.0,USD,Monday
4,2024-05-20,18:00,1,100.00%,1,-,-,0.0,0.00%,0,1,0.0,1.0,USD,Monday

In [122]:
time_week1.groupby('Weekday')['Impressions'].sum()

Weekday
Friday       662
Monday       364
Saturday    1679
Sunday      3188
Tuesday        2
Name: Impressions, dtype: int64

I will run an ANOVA tests to see if there is a variance in impressions by weekday.

In [123]:
import scipy.stats as stats

# One-way ANOVA: Testing impressions across different days
day = time_week1['Weekday']
impressions = time_week1['Impressions']

# Perform the one-way ANOVA
f_stat, p_value = stats.f_oneway(
    *[impressions[day == group] for group in time_week1['Weekday'].unique()]
)

# Output the results
print(f"F-statistic: {f_stat}")
print(f"P-value: {p_value}")

# Decision based on p-value
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between the impressions for different days.")
elif p_value < 0.1:
    print("Moderate evidence against the null hypothesis: There is a moderate difference between the impressions for different days.")
else:
    print("Fail to reject the null hypothesis: No significant difference between the impressions for different days.")

F-statistic: 25.123496883229897
P-value: 7.345207049900165e-13
Reject the null hypothesis: There is a significant difference between the impressions for different days.

In [126]:
# Perform post-hoc test using tukey HSD to see if any pairs have a p value of under 0.1 or close

tukey_results = pairwise_tukeyhsd(time_week1['Impressions'], time_week1['Weekday'], alpha=0.05)

# Display Tukey's test results
print(tukey_results)

    Multiple Comparison of Means - Tukey HSD, FWER=0.05
============================================================
 group1   group2   meandiff p-adj    lower    upper   reject
------------------------------------------------------------
  Friday   Monday  -88.9216 0.0001 -140.6812 -37.1619   True
  Friday Saturday   -40.375 0.1661  -90.1266   9.3766  False
  Friday   Sunday      22.5 0.7122  -27.2516  72.2516  False
  Friday  Tuesday -109.6667 0.0015 -186.7415 -32.5918   True
  Monday Saturday   48.5466 0.0018   13.9933  83.0999   True
  Monday   Sunday  111.4216    0.0   76.8683 145.9749   True
  Monday  Tuesday  -20.7451 0.9134  -89.0037  47.5135  False
Saturday   Sunday    62.875    0.0   31.4093  94.3407   True
Saturday  Tuesday  -69.2917  0.038 -136.0404  -2.5429   True
  Sunday  Tuesday -132.1667    0.0 -198.9154 -65.4179   True
------------------------------------------------------------

It can be seen that the date pairs friday and monday, friday and tuesday, monday and saturday, monday and sunday, saturday and sunday, saturday and tuesday and sunday and tuesday are all significantly different using an alpha of 0.5. From the data, I know Sunday is the leading day, which is why it has so many pair-wise differences.

In [128]:
time_week1.groupby('Weekday')['Clicks'].sum()

Weekday
Friday       21
Monday       10
Saturday     67
Sunday      136
Tuesday       0
Name: Clicks, dtype: int64

In [133]:
import scipy.stats as stats

# One-way ANOVA: Testing clicks across different days
day = time_week1['Weekday']
clicks = time_week1['Clicks']

# Perform the one-way ANOVA
f_stat, p_value = stats.f_oneway(
    *[clicks[day == group] for group in time_week1['Weekday'].unique()]
)

# Output the results
print(f"F-statistic: {f_stat}")
print(f"P-value: {p_value}")

# Decision based on p-value
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between the clicks for different days.")
elif p_value < 0.1:
    print("Moderate evidence against the null hypothesis: There is a moderate difference between the clicks for different days.")
else:
    print("Fail to reject the null hypothesis: No significant difference between the clicks for different days.")

F-statistic: 12.785302299505613
P-value: 7.69886663469155e-08
Reject the null hypothesis: There is a significant difference between the clicks for different days.

In [132]:
# Perform post-hoc test using tukey HSD to see if any pairs have a p value of under 0.1 or close

tukey_results = pairwise_tukeyhsd(time_week1['Clicks'], time_week1['Weekday'], alpha=0.05)

# Display Tukey's test results
print(tukey_results)

  Multiple Comparison of Means - Tukey HSD, FWER=0.05
========================================================
 group1   group2  meandiff p-adj   lower   upper  reject
--------------------------------------------------------
  Friday   Monday  -2.9118 0.0928 -6.1181  0.2946  False
  Friday Saturday  -0.7083 0.9672 -3.7903  2.3736  False
  Friday   Sunday   2.1667 0.2918 -0.9153  5.2486  False
  Friday  Tuesday     -3.5 0.2522 -8.2745  1.2745  False
  Monday Saturday   2.2034 0.0405   0.063  4.3439   True
  Monday   Sunday   5.0784    0.0   2.938  7.2189   True
  Monday  Tuesday  -0.5882  0.995 -4.8166  3.6402  False
Saturday   Sunday    2.875 0.0009  0.9258  4.8242   True
Saturday  Tuesday  -2.7917 0.3317 -6.9265  1.3432  False
  Sunday  Tuesday  -5.6667 0.0024 -9.8015 -1.5318   True
--------------------------------------------------------

It can be seen that the day friday and saturday, friday and sunday, friday and tuesday, monday and tuesday, and saturday and tuesday are the only ones not significantly different. From the data, I know Sunday is the leading day, which is why it has so many pair-wise differences. Also, Friday is the second leading day, which is why Friday and Sunday are not significantly different.

In [115]:
time_week1.groupby('Date')['Conversions'].sum()

Date
2024-05-17    11
2024-05-18    28
2024-05-19    37
2024-05-20     3
2024-05-21     0
Name: Conversions, dtype: int64

In [139]:
import scipy.stats as stats

# One-way ANOVA: Testing conversions across different days
day = time_week1['Weekday']
conv = time_week1['Conversions']

# Perform the one-way ANOVA
f_stat, p_value = stats.f_oneway(
    *[conv[day == group] for group in time_week1['Weekday'].unique()]
)

# Output the results
print(f"F-statistic: {f_stat}")
print(f"P-value: {p_value}")

# Decision based on p-value
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between the conversions for different days.")
elif p_value < 0.1:
    print("Moderate evidence against the null hypothesis: There is a moderate difference between the conversions for different days.")
else:
    print("Fail to reject the null hypothesis: No significant difference between the conversions for different days.")

F-statistic: 4.218264636299403
P-value: 0.004103409418643862
Reject the null hypothesis: There is a significant difference between the conversions for different days.

In [136]:
# Perform post-hoc test using tukey HSD to see if any pairs have a p value of under 0.1 or close

tukey_results = pairwise_tukeyhsd(time_week1['Conversions'], time_week1['Weekday'], alpha=0.05)

# Display Tukey's test results
print(tukey_results)

  Multiple Comparison of Means - Tukey HSD, FWER=0.05
========================================================
 group1   group2  meandiff p-adj   lower   upper  reject
--------------------------------------------------------
  Friday   Monday  -1.6569 0.0492 -3.3102 -0.0035   True
  Friday Saturday  -0.6667 0.7654 -2.2558  0.9225  False
  Friday   Sunday  -0.2917 0.9857 -1.8808  1.2975  False
  Friday  Tuesday  -1.8333 0.2379 -4.2953  0.6286  False
  Monday Saturday   0.9902 0.0995 -0.1135  2.0939  False
  Monday   Sunday   1.3652 0.0079  0.2615  2.4689   True
  Monday  Tuesday  -0.1765 0.9994 -2.3568  2.0039  False
Saturday   Sunday    0.375 0.8334 -0.6301  1.3801  False
Saturday  Tuesday  -1.1667 0.5451 -3.2988  0.9654  False
  Sunday  Tuesday  -1.5417  0.265 -3.6738  0.5904  False
--------------------------------------------------------

The conversion rates by weekday were more alike than both the impressions and clicks.

In [137]:
time_week2.groupby('Weekday')['Impressions'].sum()

Weekday
Friday          1
Monday       1698
Thursday      571
Tuesday      3383
Wednesday    3956
Name: Impressions, dtype: int64

In [160]:
import scipy.stats as stats

# One-way ANOVA: Testing impressions across different days
day = time_week2['Weekday']
impressions = time_week2['Impressions']

# Perform the one-way ANOVA
f_stat, p_value = stats.f_oneway(
    *[impressions[day == group] for group in time_week2['Weekday'].unique()]
)

# Output the results
print(f"F-statistic: {f_stat}")
print(f"P-value: {p_value}")

# Decision based on p-value
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between the impressions for different days.")
elif p_value < 0.1:
    print("Moderate evidence against the null hypothesis: There is a moderate difference between the impressions for different days.")
else:
    print("Fail to reject the null hypothesis: No significant difference between the impressions for different days.")

F-statistic: nan
P-value: nan
Fail to reject the null hypothesis: No significant difference between the impressions for different days.

/usr/local/lib/python3.11/dist-packages/scipy/stats/_stats_py.py:4102: DegenerateDataWarning: all input arrays have length 1.  f_oneway requires that at least one input has length greater than 1.
  if _f_oneway_is_too_small(samples):

In [142]:
# Perform post-hoc test using tukey HSD to see if any pairs have a p value of under 0.1 or close

tukey_results = pairwise_tukeyhsd(time_week2['Conversions'], time_week2['Weekday'], alpha=0.05)

# Display Tukey's test results
print(tukey_results)

Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================
 group1    group2  meandiff p-adj lower upper reject
----------------------------------------------------
  Friday    Monday     34.0   nan   nan   nan  False
  Friday  Thursday      2.0   nan   nan   nan  False
  Friday   Tuesday     34.0   nan   nan   nan  False
  Friday Wednesday     27.0   nan   nan   nan  False
  Monday  Thursday    -32.0   nan   nan   nan  False
  Monday   Tuesday      0.0   nan   nan   nan  False
  Monday Wednesday     -7.0   nan   nan   nan  False
Thursday   Tuesday     32.0   nan   nan   nan  False
Thursday Wednesday     25.0   nan   nan   nan  False
 Tuesday Wednesday     -7.0   nan   nan   nan  False
----------------------------------------------------

/usr/local/lib/python3.11/dist-packages/numpy/core/fromnumeric.py:3787: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.11/dist-packages/numpy/core/_methods.py:198: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

I am unable to do a one way ANOVA test, most likely because there is not enough data gathered for week 2, as I was not provided time data for week 2. Therefore, I will do a manual analysis for the sake of the project.

In [147]:
time_week2.groupby('Weekday')['Impressions'].sum().sort_values(ascending=False)

Weekday
Wednesday    3956
Tuesday      3383
Monday       1698
Thursday      571
Friday          1
Name: Impressions, dtype: int64

There is clearly not much difference between Wednesday and Tuesday, but Monday, had an almost 50% drop, with Thursday having around an 85% drop, which is safe to say in this case that they are different.

In [148]:
time_week2.groupby('Weekday')['Clicks'].sum().sort_values(ascending=False)

Weekday
Wednesday    116
Tuesday       94
Monday        78
Thursday      13
Friday         0
Name: Clicks, dtype: int64

Again, Wednesday and Tuesday are very close, and this time Monday is not that different either, with only about a 30% change from Wednesday and a 17% decrease from Tuesday. However, Thursday and Friday are low.

In [149]:
time_week2.groupby('Weekday')['Conversions'].sum().sort_values(ascending=False)

Weekday
Monday       34
Tuesday      34
Wednesday    27
Thursday      2
Friday        0
Name: Conversions, dtype: int64

Finally, Monday, Tuesday, and Wednesday recieved relatively the same amount of conversions, but Thursday and Friday recieved a significant amount less.

In [152]:
import scipy.stats as stats

# One-way ANOVA: Testing impressions across different days
hour = time_week1['Hour']
impressions = time_week1['Impressions']

# Perform the one-way ANOVA
f_stat, p_value = stats.f_oneway(
    *[impressions[hour == group] for group in time_week1['Hour'].unique()]
)

# Output the results
print(f"F-statistic: {f_stat}")
print(f"P-value: {p_value}")

# Decision based on p-value
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between the impressions for different times.")
elif p_value < 0.1:
    print("Moderate evidence against the null hypothesis: There is a moderate difference between the impressions for different times.")
else:
    print("Fail to reject the null hypothesis: No significant difference between the impressions for different times.")

F-statistic: 0.6366794490234077
P-value: 0.8801486163223359
Fail to reject the null hypothesis: No significant difference between the impressions for different times.

In [154]:
# Perform post-hoc test using tukey HSD to see if any pairs have a p value of under 0.1 or close

tukey_results = pairwise_tukeyhsd(time_week1['Impressions'], time_week1['Hour'], alpha=0.05)

# Display Tukey's test results
print(tukey_results)

  Multiple Comparison of Means - Tukey HSD, FWER=0.05
========================================================
group1 group2  meandiff p-adj    lower    upper   reject
--------------------------------------------------------
  0:00  10:00    0.6667    1.0 -197.1773 198.5107  False
  0:00  11:00      -6.0    1.0  -203.844  191.844  False
  0:00  12:00       5.0    1.0  -192.844  202.844  False
  0:00  13:00    4.6667    1.0 -193.1773 202.5107  False
  0:00  14:00    0.3333    1.0 -197.5107 198.1773  False
  0:00  15:00   10.8333    1.0  -210.363 232.0296  False
  0:00  16:00   -9.9167    1.0 -194.9828 175.1494  False
  0:00  17:00      19.0    1.0  -178.844  216.844  False
  0:00  18:00    0.8333    1.0 -184.2328 185.8994  False
  0:00  19:00    8.5833    1.0 -176.4828 193.6494  False
  0:00   1:00  -10.3333    1.0 -208.1773 187.5107  False
  0:00  20:00  114.6667 0.8369  -83.1773 312.5107  False
  0:00  21:00      37.0    1.0  -160.844  234.844  False
  0:00  22:00      43.0    1.0  -154.844  240.844  False
  0:00  23:00   18.6667    1.0 -179.1773 216.5107  False
  0:00   2:00      -9.0    1.0  -206.844  188.844  False
  0:00   3:00  -16.6667    1.0 -214.5107 181.1773  False
  0:00   4:00     -12.0    1.0  -209.844  185.844  False
  0:00   5:00  -15.3333    1.0 -213.1773 182.5107  False
  0:00   6:00  -32.6667    1.0 -217.7328 152.3994  False
  0:00   7:00  -11.3333    1.0 -209.1773 186.5107  False
  0:00   8:00   22.8333    1.0  -198.363 244.0296  False
  0:00   9:00    7.3333    1.0 -190.5107 205.1773  False
 10:00  11:00   -6.6667    1.0 -204.5107 191.1773  False
 10:00  12:00    4.3333    1.0 -193.5107 202.1773  False
 10:00  13:00       4.0    1.0  -193.844  201.844  False
 10:00  14:00   -0.3333    1.0 -198.1773 197.5107  False
 10:00  15:00   10.1667    1.0 -211.0296  231.363  False
 10:00  16:00  -10.5833    1.0 -195.6494 174.4828  False
 10:00  17:00   18.3333    1.0 -179.5107 216.1773  False
 10:00  18:00    0.1667    1.0 -184.8994 185.2328  False
 10:00  19:00    7.9167    1.0 -177.1494 192.9828  False
 10:00   1:00     -11.0    1.0  -208.844  186.844  False
 10:00  20:00     114.0 0.8435   -83.844  311.844  False
 10:00  21:00   36.3333    1.0 -161.5107 234.1773  False
 10:00  22:00   42.3333    1.0 -155.5107 240.1773  False
 10:00  23:00      18.0    1.0  -179.844  215.844  False
 10:00   2:00   -9.6667    1.0 -207.5107 188.1773  False
 10:00   3:00  -17.3333    1.0 -215.1773 180.5107  False
 10:00   4:00  -12.6667    1.0 -210.5107 185.1773  False
 10:00   5:00     -16.0    1.0  -213.844  181.844  False
 10:00   6:00  -33.3333    1.0 -218.3994 151.7328  False
 10:00   7:00     -12.0    1.0  -209.844  185.844  False
 10:00   8:00   22.1667    1.0 -199.0296  243.363  False
 10:00   9:00    6.6667    1.0 -191.1773 204.5107  False
 11:00  12:00      11.0    1.0  -186.844  208.844  False
 11:00  13:00   10.6667    1.0 -187.1773 208.5107  False
 11:00  14:00    6.3333    1.0 -191.5107 204.1773  False
 11:00  15:00   16.8333    1.0  -204.363 238.0296  False
 11:00  16:00   -3.9167    1.0 -188.9828 181.1494  False
 11:00  17:00      25.0    1.0  -172.844  222.844  False
 11:00  18:00    6.8333    1.0 -178.2328 191.8994  False
 11:00  19:00   14.5833    1.0 -170.4828 199.6494  False
 11:00   1:00   -4.3333    1.0 -202.1773 193.5107  False
 11:00  20:00  120.6667 0.7713  -77.1773 318.5107  False
 11:00  21:00      43.0    1.0  -154.844  240.844  False
 11:00  22:00      49.0    1.0  -148.844  246.844  False
 11:00  23:00   24.6667    1.0 -173.1773 222.5107  False
 11:00   2:00      -3.0    1.0  -200.844  194.844  False
 11:00   3:00  -10.6667    1.0 -208.5107 187.1773  False
 11:00   4:00      -6.0    1.0  -203.844  191.844  False
 11:00   5:00   -9.3333    1.0 -207.1773 188.5107  False
 11:00   6:00  -26.6667    1.0 -211.7328 158.3994  False
 11:00   7:00   -5.3333    1.0 -203.1773 192.5107  False
 11:00   8:00   28.8333    1.0  -192.363 250.0296  False
 11:00   9:00   13.3333    1.0 -184.5107 211.1773  False
 12:00  13:00   -0.3333    1.0 -198.1773 197.5107  False
 12:00  14:00   -4.6667    1.0 -202.5107 193.1773  False
 12:00  15:00    5.8333    1.0  -215.363 227.0296  False
 12:00  16:00  -14.9167    1.0 -199.9828 170.1494  False
 12:00  17:00      14.0    1.0  -183.844  211.844  False
 12:00  18:00   -4.1667    1.0 -189.2328 180.8994  False
 12:00  19:00    3.5833    1.0 -181.4828 188.6494  False
 12:00   1:00  -15.3333    1.0 -213.1773 182.5107  False
 12:00  20:00  109.6667 0.8828  -88.1773 307.5107  False
 12:00  21:00      32.0    1.0  -165.844  229.844  False
 12:00  22:00      38.0    1.0  -159.844  235.844  False
 12:00  23:00   13.6667    1.0 -184.1773 211.5107  False
 12:00   2:00     -14.0    1.0  -211.844  183.844  False
 12:00   3:00  -21.6667    1.0 -219.5107 176.1773  False
 12:00   4:00     -17.0    1.0  -214.844  180.844  False
 12:00   5:00  -20.3333    1.0 -218.1773 177.5107  False
 12:00   6:00  -37.6667    1.0 -222.7328 147.3994  False
 12:00   7:00  -16.3333    1.0 -214.1773 181.5107  False
 12:00   8:00   17.8333    1.0  -203.363 239.0296  False
 12:00   9:00    2.3333    1.0 -195.5107 200.1773  False
 13:00  14:00   -4.3333    1.0 -202.1773 193.5107  False
 13:00  15:00    6.1667    1.0 -215.0296  227.363  False
 13:00  16:00  -14.5833    1.0 -199.6494 170.4828  False
 13:00  17:00   14.3333    1.0 -183.5107 212.1773  False
 13:00  18:00   -3.8333    1.0 -188.8994 181.2328  False
 13:00  19:00    3.9167    1.0 -181.1494 188.9828  False
 13:00   1:00     -15.0    1.0  -212.844  182.844  False
 13:00  20:00     110.0 0.8801   -87.844  307.844  False
 13:00  21:00   32.3333    1.0 -165.5107 230.1773  False
 13:00  22:00   38.3333    1.0 -159.5107 236.1773  False
 13:00  23:00      14.0    1.0  -183.844  211.844  False
 13:00   2:00  -13.6667    1.0 -211.5107 184.1773  False
 13:00   3:00  -21.3333    1.0 -219.1773 176.5107  False
 13:00   4:00  -16.6667    1.0 -214.5107 181.1773  False
 13:00   5:00     -20.0    1.0  -217.844  177.844  False
 13:00   6:00  -37.3333    1.0 -222.3994 147.7328  False
 13:00   7:00     -16.0    1.0  -213.844  181.844  False
 13:00   8:00   18.1667    1.0 -203.0296  239.363  False
 13:00   9:00    2.6667    1.0 -195.1773 200.5107  False
 14:00  15:00      10.5    1.0 -210.6963 231.6963  False
 14:00  16:00    -10.25    1.0 -195.3161 174.8161  False
 14:00  17:00   18.6667    1.0 -179.1773 216.5107  False
 14:00  18:00       0.5    1.0 -184.5661 185.5661  False
 14:00  19:00      8.25    1.0 -176.8161 193.3161  False
 14:00   1:00  -10.6667    1.0 -208.5107 187.1773  False
 14:00  20:00  114.3333 0.8403  -83.5107 312.1773  False
 14:00  21:00   36.6667    1.0 -161.1773 234.5107  False
 14:00  22:00   42.6667    1.0 -155.1773 240.5107  False
 14:00  23:00   18.3333    1.0 -179.5107 216.1773  False
 14:00   2:00   -9.3333    1.0 -207.1773 188.5107  False
 14:00   3:00     -17.0    1.0  -214.844  180.844  False
 14:00   4:00  -12.3333    1.0 -210.1773 185.5107  False
 14:00   5:00  -15.6667    1.0 -213.5107 182.1773  False
 14:00   6:00     -33.0    1.0 -218.0661 152.0661  False
 14:00   7:00  -11.6667    1.0 -209.5107 186.1773  False
 14:00   8:00      22.5    1.0 -198.6963 243.6963  False
 14:00   9:00       7.0    1.0  -190.844  204.844  False
 15:00  16:00    -20.75    1.0 -230.5953 189.0953  False
 15:00  17:00    8.1667    1.0 -213.0296  229.363  False
 15:00  18:00     -10.0    1.0 -219.8453 199.8453  False
 15:00  19:00     -2.25    1.0 -212.0953 207.5953  False
 15:00   1:00  -21.1667    1.0  -242.363 200.0296  False
 15:00  20:00  103.8333 0.9744  -117.363 325.0296  False
 15:00  21:00   26.1667    1.0 -195.0296  247.363  False
 15:00  22:00   32.1667    1.0 -189.0296  253.363  False
 15:00  23:00    7.8333    1.0  -213.363 229.0296  False
 15:00   2:00  -19.8333    1.0 -241.0296  201.363  False
 15:00   3:00     -27.5    1.0 -248.6963 193.6963  False
 15:00   4:00  -22.8333    1.0 -244.0296  198.363  False
 15:00   5:00  -26.1667    1.0  -247.363 195.0296  False
 15:00   6:00     -43.5    1.0 -253.3453 166.3453  False
 15:00   7:00  -22.1667    1.0  -243.363 199.0296  False
 15:00   8:00      12.0    1.0 -230.3084 254.3084  False
 15:00   9:00      -3.5    1.0 -224.6963 217.6963  False
 16:00  17:00   28.9167    1.0 -156.1494 213.9828  False
 16:00  18:00     10.75    1.0 -160.5879 182.0879  False
 16:00  19:00      18.5    1.0 -152.8379 189.8379  False
 16:00   1:00   -0.4167    1.0 -185.4828 184.6494  False
 16:00  20:00  124.5833 0.6087  -60.4828 309.6494  False
 16:00  21:00   46.9167    1.0 -138.1494 231.9828  False
 16:00  22:00   52.9167    1.0 -132.1494 237.9828  False
 16:00  23:00   28.5833    1.0 -156.4828 213.6494  False
 16:00   2:00    0.9167    1.0 -184.1494 185.9828  False
 16:00   3:00     -6.75    1.0 -191.8161 178.3161  False
 16:00   4:00   -2.0833    1.0 -187.1494 182.9828  False
 16:00   5:00   -5.4167    1.0 -190.4828 179.6494  False
 16:00   6:00    -22.75    1.0 -194.0879 148.5879  False
 16:00   7:00   -1.4167    1.0 -186.4828 183.6494  False
 16:00   8:00     32.75    1.0 -177.0953 242.5953  False
 16:00   9:00     17.25    1.0 -167.8161 202.3161  False
 17:00  18:00  -18.1667    1.0 -203.2328 166.8994  False
 17:00  19:00  -10.4167    1.0 -195.4828 174.6494  False
 17:00   1:00  -29.3333    1.0 -227.1773 168.5107  False
 17:00  20:00   95.6667 0.9653 -102.1773 293.5107  False
 17:00  21:00      18.0    1.0  -179.844  215.844  False
 17:00  22:00      24.0    1.0  -173.844  221.844  False
 17:00  23:00   -0.3333    1.0 -198.1773 197.5107  False
 17:00   2:00     -28.0    1.0  -225.844  169.844  False
 17:00   3:00  -35.6667    1.0 -233.5107 162.1773  False
 17:00   4:00     -31.0    1.0  -228.844  166.844  False
 17:00   5:00  -34.3333    1.0 -232.1773 163.5107  False
 17:00   6:00  -51.6667    1.0 -236.7328 133.3994  False
 17:00   7:00  -30.3333    1.0 -228.1773 167.5107  False
 17:00   8:00    3.8333    1.0  -217.363 225.0296  False
 17:00   9:00  -11.6667    1.0 -209.5107 186.1773  False
 18:00  19:00      7.75    1.0 -163.5879 179.0879  False
 18:00   1:00  -11.1667    1.0 -196.2328 173.8994  False
 18:00  20:00  113.8333  0.759  -71.2328 298.8994  False
 18:00  21:00   36.1667    1.0 -148.8994 221.2328  False
 18:00  22:00   42.1667    1.0 -142.8994 227.2328  False
 18:00  23:00   17.8333    1.0 -167.2328 202.8994  False
 18:00   2:00   -9.8333    1.0 -194.8994 175.2328  False
 18:00   3:00     -17.5    1.0 -202.5661 167.5661  False
 18:00   4:00  -12.8333    1.0 -197.8994 172.2328  False
 18:00   5:00  -16.1667    1.0 -201.2328 168.8994  False
 18:00   6:00     -33.5    1.0 -204.8379 137.8379  False
 18:00   7:00  -12.1667    1.0 -197.2328 172.8994  False
 18:00   8:00      22.0    1.0 -187.8453 231.8453  False
 18:00   9:00       6.5    1.0 -178.5661 191.5661  False
 19:00   1:00  -18.9167    1.0 -203.9828 166.1494  False
 19:00  20:00  106.0833 0.8493  -78.9828 291.1494  False
 19:00  21:00   28.4167    1.0 -156.6494 213.4828  False
 19:00  22:00   34.4167    1.0 -150.6494 219.4828  False
 19:00  23:00   10.0833    1.0 -174.9828 195.1494  False
 19:00   2:00  -17.5833    1.0 -202.6494 167.4828  False
 19:00   3:00    -25.25    1.0 -210.3161 159.8161  False
 19:00   4:00  -20.5833    1.0 -205.6494 164.4828  False
 19:00   5:00  -23.9167    1.0 -208.9828 161.1494  False
 19:00   6:00    -41.25    1.0 -212.5879 130.0879  False
 19:00   7:00  -19.9167    1.0 -204.9828 165.1494  False
 19:00   8:00     14.25    1.0 -195.5953 224.0953  False
 19:00   9:00     -1.25    1.0 -186.3161 183.8161  False
  1:00  20:00     125.0 0.7179   -72.844  322.844  False
  1:00  21:00   47.3333    1.0 -150.5107 245.1773  False
  1:00  22:00   53.3333    1.0 -144.5107 251.1773  False
  1:00  23:00      29.0    1.0  -168.844  226.844  False
  1:00   2:00    1.3333    1.0 -196.5107 199.1773  False
  1:00   3:00   -6.3333    1.0 -204.1773 191.5107  False
  1:00   4:00   -1.6667    1.0 -199.5107 196.1773  False
  1:00   5:00      -5.0    1.0  -202.844  192.844  False
  1:00   6:00  -22.3333    1.0 -207.3994 162.7328  False
  1:00   7:00      -1.0    1.0  -198.844  196.844  False
  1:00   8:00   33.1667    1.0 -188.0296  254.363  False
  1:00   9:00   17.6667    1.0 -180.1773 215.5107  False
 20:00  21:00  -77.6667 0.9969 -275.5107 120.1773  False
 20:00  22:00  -71.6667  0.999 -269.5107 126.1773  False
 20:00  23:00     -96.0  0.964  -293.844  101.844  False
 20:00   2:00 -123.6667 0.7348 -321.5107  74.1773  False
 20:00   3:00 -131.3333  0.634 -329.1773  66.5107  False
 20:00   4:00 -126.6667 0.6964 -324.5107  71.1773  False
 20:00   5:00    -130.0 0.6521  -327.844   67.844  False
 20:00   6:00 -147.3333 0.2982 -332.3994  37.7328  False
 20:00   7:00    -126.0 0.7051  -323.844   71.844  False
 20:00   8:00  -91.8333 0.9937 -313.0296  129.363  False
 20:00   9:00 -107.3333 0.9013 -305.1773  90.5107  False
 21:00  22:00       6.0    1.0  -191.844  203.844  False
 21:00  23:00  -18.3333    1.0 -216.1773 179.5107  False
 21:00   2:00     -46.0    1.0  -243.844  151.844  False
 21:00   3:00  -53.6667    1.0 -251.5107 144.1773  False
 21:00   4:00     -49.0    1.0  -246.844  148.844  False
 21:00   5:00  -52.3333    1.0 -250.1773 145.5107  False
 21:00   6:00  -69.6667 0.9982 -254.7328 115.3994  False
 21:00   7:00  -48.3333    1.0 -246.1773 149.5107  False
 21:00   8:00  -14.1667    1.0  -235.363 207.0296  False
 21:00   9:00  -29.6667    1.0 -227.5107 168.1773  False
 22:00  23:00  -24.3333    1.0 -222.1773 173.5107  False
 22:00   2:00     -52.0    1.0  -249.844  145.844  False
 22:00   3:00  -59.6667 0.9999 -257.5107 138.1773  False
 22:00   4:00     -55.0    1.0  -252.844  142.844  False
 22:00   5:00  -58.3333    1.0 -256.1773 139.5107  False
 22:00   6:00  -75.6667 0.9948 -260.7328 109.3994  False
 22:00   7:00  -54.3333    1.0 -252.1773 143.5107  False
 22:00   8:00  -20.1667    1.0  -241.363 201.0296  False
 22:00   9:00  -35.6667    1.0 -233.5107 162.1773  False
 23:00   2:00  -27.6667    1.0 -225.5107 170.1773  False
 23:00   3:00  -35.3333    1.0 -233.1773 162.5107  False
 23:00   4:00  -30.6667    1.0 -228.5107 167.1773  False
 23:00   5:00     -34.0    1.0  -231.844  163.844  False
 23:00   6:00  -51.3333    1.0 -236.3994 133.7328  False
 23:00   7:00     -30.0    1.0  -227.844  167.844  False
 23:00   8:00    4.1667    1.0 -217.0296  225.363  False
 23:00   9:00  -11.3333    1.0 -209.1773 186.5107  False
  2:00   3:00   -7.6667    1.0 -205.5107 190.1773  False
  2:00   4:00      -3.0    1.0  -200.844  194.844  False
  2:00   5:00   -6.3333    1.0 -204.1773 191.5107  False
  2:00   6:00  -23.6667    1.0 -208.7328 161.3994  False
  2:00   7:00   -2.3333    1.0 -200.1773 195.5107  False
  2:00   8:00   31.8333    1.0  -189.363 253.0296  False
  2:00   9:00   16.3333    1.0 -181.5107 214.1773  False
  3:00   4:00    4.6667    1.0 -193.1773 202.5107  False
  3:00   5:00    1.3333    1.0 -196.5107 199.1773  False
  3:00   6:00     -16.0    1.0 -201.0661 169.0661  False
  3:00   7:00    5.3333    1.0 -192.5107 203.1773  False
  3:00   8:00      39.5    1.0 -181.6963 260.6963  False
  3:00   9:00      24.0    1.0  -173.844  221.844  False
  4:00   5:00   -3.3333    1.0 -201.1773 194.5107  False
  4:00   6:00  -20.6667    1.0 -205.7328 164.3994  False
  4:00   7:00    0.6667    1.0 -197.1773 198.5107  False
  4:00   8:00   34.8333    1.0  -186.363 256.0296  False
  4:00   9:00   19.3333    1.0 -178.5107 217.1773  False
  5:00   6:00  -17.3333    1.0 -202.3994 167.7328  False
  5:00   7:00       4.0    1.0  -193.844  201.844  False
  5:00   8:00   38.1667    1.0 -183.0296  259.363  False
  5:00   9:00   22.6667    1.0 -175.1773 220.5107  False
  6:00   7:00   21.3333    1.0 -163.7328 206.3994  False
  6:00   8:00      55.5    1.0 -154.3453 265.3453  False
  6:00   9:00      40.0    1.0 -145.0661 225.0661  False
  7:00   8:00   34.1667    1.0 -187.0296  255.363  False
  7:00   9:00   18.6667    1.0 -179.1773 216.5107  False
  8:00   9:00     -15.5    1.0 -236.6963 205.6963  False
--------------------------------------------------------

In [155]:
tukey_results.pvalues < 0.1

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [162]:
time_week1.groupby('Hour')['Impressions'].sum().sort_values(ascending=False).head(10)

Hour
20:00    565
22:00    350
21:00    332
19:00    329
18:00    298
17:00    278
23:00    277
16:00    255
9:00     243
12:00    236
Name: Impressions, dtype: int64

# Results

## Demographics

In this analysis, I explored the relationship between user demographics (gender and age) and key performance indicators (KPIs) such as impressions, clicks, and conversions. The goal was to understand if there were statistically significant differences between men and women in terms of these metrics and if age had any impact on conversion and click-through rates (CTR).

To achieve this, I applied a series of hypothesis tests and analysis of variance (ANOVA) techniques, including:

1. **Hypothesis Test for Gender Differences**: I performed a hypothesis test to determine whether women had more impressions, clicks, and conversions than men. Using the resultant p-value and an alpha of 0.05, women have a statisitically different amount of impressions and clicks. However, there is no difference in conversions between men and women.
  
2. **2-Way Z-Test for Conversion (CVR) and Click Rates (CTR)**: A two-way z-test was used to investigate conversion and click rates by gender. Using an alpha of 0.05 again, it was found that there is no significant difference between CVR or CTR for men and women. Even though women were the majority of impressions and clicks, they both had the same overall CVR and CTR.
  
3. **One-Way ANOVA for Age Effect**: I conducted a one-way ANOVA to assess whether age influenced conversion rates, as it was revealed gender does not. The test revealed that age had no significant effect on CVR.

4. **One-Way ANOVA for Gender and KPIs**: A one-way ANOVA was also performed to see if gender had an effect on conversion rates. The test revealed that gender had no significant effect on CVR, which can be seen in the z-test as well.

5. **Two-Way ANOVA with Post-Hoc Tukey Test**: To refine the analysis, a two-way ANOVA with a post-hoc Tukey test was applied to assess the effect of both age and gender on conversion rates. Using a 0.05 value for alpha, there was no significant difference between any of the categories. However, upon further analysis in the post-hoc tukey test, it was found that the following pairs had a p value of less than 0.1, which is also a valid alpha choice.
  - Age groups 18-25 and 55+
  - Women in the age group 18-25 and men in the age group 55+

 This suggests that older age groups, and older men specifically, are more likely to convert than the younger age groups, young women specifically. This makes sense, as older age groups are more likely to have money to spend on entertainment than the younger age groups.

This series of analyses provides valuable insights into how user demographics may affect conversion behaviors and helps identify actionable trends for improving performance across different user groups.

## Time Analysis

 For this analysis, I examined data from an advertising campaign that was run over the course of two different weeks.

 **Week 1**, I performed a one-way ANOVA test to determine if there were significant differences in impressions, clicks, and conversions across different days of the week. The results revealed a significant difference, with Sunday leading in all three metrics, followed by Saturday. To further explore the differences between the days, I used a post-hoc Tukey test, which compared all the days in pairs.

**Week 2**, I found that the data was insufficient to run an ANOVA test, so I evaluated the trends manually. I observed that Wednesday and Tuesday outperformed the other days in impressions, clicks, and conversions. Monday lagged behind in impressions and clicks but was relatively consistent with other days in terms of conversions. Thursday and Friday consistently had low performance across all metrics.

Lastly, I conducted an ANOVA test for impressions by hour of the day for week 1. The results showed no significant variance between hours, even with a p-value < 0.1. However, I did identify that the top 5 times for impressions were consistently around 300 impressions, with the peak time being over 500 impressions. The top 5 times, in order, were: 8 PM, 10 PM, 9 PM, 7 PM, and 6 PM—all occurring during the evening when people are generally more available after work and school.